# frontend/Dockerfile.dev
FROM node:16-alpine

WORKDIR /app

# Create necessary directories and set permissions
RUN mkdir -p /app/node_modules/.cache && \
    chown -R node:node /app

USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 3000
CMD ["npm", "start"]