# docker-compose.yml (for production)
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://170.64.202.114:5000
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/knowledge-base?authSource=admin&directConnection=true
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/markdown-files:/app/markdown-files:ro
      - ./backend/markdown-files-manual:/app/markdown-files-manual:ro
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/knowledge-base --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: