# backend/Dockerfile.dev
FROM node:16-alpine

WORKDIR /app

# Add node user and set ownership
RUN mkdir -p /app/markdown-downloads && \
    addgroup -S appgroup && adduser -S appuser -G appgroup && \
    chown -R appuser:appgroup /app

# Ensure the non-root user has write permissions
RUN chmod -R 777 /app/markdown-downloads

# Switch to non-root user
USER appuser

COPY --chown=appuser:appgroup package*.json ./
RUN npm install

COPY --chown=appuser:appgroup . .

EXPOSE 5000
CMD ["npm", "run", "dev"]